# Generated by Django 5.0.3 on 2024-04-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signed_in',
            field=models.BooleanField(default=False),
        ),
    ]
