# Generated by Django 5.0.3 on 2024-05-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follow',
        ),
    ]
